name: tests

on:
  pull_request:

jobs:
  tests:
    name: tests
    runs-on: ubuntu-latest
    steps:
    - name: Check out the repository
      uses: actions/checkout@v3

    - name: Set up Python 3.x
      uses: actions/setup-python@v3
      with:
        python-version: 3.10.8

    - name: Install dependencies
      run: |
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        if [ -f requirements-test.txt ]; then pip install -r requirements-test.txt; fi

    - name: Run pytest
      continue-on-error: true
      run: |
        if [ -d tests/ ]; then
          code=$(
            coverage run --source=src/ -m pytest tests/ > test_report.txt
            echo $?
          )
          echo $code > exit_code.txt
        else
          echo 0 > exit_code.txt
        fi
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}