name: tests

on:
  pull_request:

jobs:
  tests:
    name: tests
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Set up Python 3.x
        uses: actions/setup-python@v3
        with:
          python-version: 3.10.8

      - name: Install dependencies
        run: |
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          if [ -f requirements-test.txt ]; then pip install -r requirements-test.txt; fi

      - name: Debug Information
        run: |
          echo "Current directory: $(pwd)"
          echo "Contents of the directory: $(ls -l)"
          echo "Python version: $(python --version)"
          echo "Installed packages: $(pip list)"
          echo "GitHub Token: $GITHUB_TOKEN"

      - name: Run pytest
        continue-on-error: true
        run: |
          if [ -d tests/ ]; then
            coverage run --source=src/ -m pytest tests/ > test_report.txt
            echo "Pytest exit code: $?"
          else
            echo "Tests directory not found."
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
